name: Run Gradle on PRs
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: list tasks
      run: ./gradlew -q :tasks --all

    - name: Execute Gradle build
      run: ./gradlew clean test assemble
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRERELEASE: No
        
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1
    
    - name: Upload folder to S3
      run: |
        aws s3 sync build/libs/ s3://afs1-prod-cldfrc-gocd-gocd-build-dependencies/gocd-s3-artifact-plugin-cldfrc
